annotations:
  min_scale_version: 24.10.2.2
app_version: 2.3.2.5245
capabilities: []
categories:
- media
changelog_url: https://github.com/Prowlarr/Prowlarr/releases
date_added: '2024-07-31'
description: Prowlarr is an indexer manager/proxy to integrate with your various PVR
  apps.
home: https://prowlarr.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/prowlarr/icons/icon.png
keywords:
- indexer
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: prowlarr
run_as_context:
- description: Container [prowlarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/prowlarr/screenshots/screenshot1.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/prowlarr
- https://prowlarr.com
title: Prowlarr
train: community
version: 1.5.2
