annotations:
  min_scale_version: 24.10.2.2
app_version: v3.4.6
capabilities: []
categories:
- networking
changelog_url: https://github.com/FlareSolverr/FlareSolverr/blob/master/CHANGELOG.md
date_added: '2024-10-24'
description: FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.
home: https://github.com/FlareSolverr/FlareSolverr
host_mounts: []
icon: https://media.sys.truenas.net/apps/flaresolverr/icons/icon.svg
keywords:
- networking
- captcha
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: flaresolverr
run_as_context:
- description: Container [flaresolverr] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/FlareSolverr/FlareSolverr
title: FlareSolverr
train: community
version: 1.2.2
