annotations:
  min_scale_version: 24.10.2.2
app_version: 2.7.3
capabilities: []
categories:
- media
changelog_url: https://github.com/fallenbagel/jellyseerr/releases
date_added: '2024-08-02'
description: Jellyseerr is a free and open source software application for managing
  requests for your media library.
home: https://github.com/Fallenbagel/jellyseerr
host_mounts: []
icon: https://media.sys.truenas.net/apps/jellyseerr/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jellyseerr
run_as_context:
- description: Container [jellyseerr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/jellyseerr/screenshots/screenshot1.png
sources:
- https://github.com/Fallenbagel/jellyseerr
- https://hub.docker.com/r/fallenbagel/jellyseerr
title: Jellyseerr (Deprecated)
train: community
version: 1.3.2
